"""added relationship on User

Revision ID: 4b7d4672fcd3
Revises: 4ef45c28374c
Create Date: 2018-03-14 02:57:49.836246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7d4672fcd3'
down_revision = '4ef45c28374c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    # ### end Alembic commands ###
