"""added urole

Revision ID: f768b2a088a6
Revises: 0e296ab584fb
Create Date: 2018-03-08 22:33:16.287449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f768b2a088a6'
down_revision = '0e296ab584fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('urole', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_user_urole'), 'user', ['urole'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_urole'), table_name='user')
    op.drop_column('user', 'urole')
    # ### end Alembic commands ###
